# assoc .txt
cmd /c ftype  JSFile="C:\Windows\notepad.exe" "%1"
cmd /c ftype VBEFile="C:\Windows\notepad.exe" "%1"
cmd /c ftype VBSFile="C:\Windows\notepad.exe" "%1"
cmd /c ftype JSEFile="C:\Windows\notepad.exe" "%1"
cmd /c ftype WSFFile="C:\Windows\notepad.exe" "%1"
cmd /c ftype WSHFile="C:\Windows\notepad.exe" "%1"
cmd /c ftype regfile="C:\Windows\notepad.exe" "%1"
cmd /c ftype inffile="C:\Windows\notepad.exe" "%1"
cmd /c ftype scriptletfile="C:\Windows\notepad.exe" "%1"
cmd /c ftype Microsoft.PowerShellScript.1="C:\Windows\notepad.exe" "%1"
cmd /c ftype Microsoft.PowerShellXMLData.1="C:\Windows\notepad.exe" "%1"
cmd /c ftype Microsoft.PowerShellConsole.1="C:\Windows\notepad.exe" "%1"
cmd /c ftype "XML Script Engine"="C:\Windows\notepad.exe" "%1"
